export const sliderImages = [

    require ('../Images/1.jpg'),
    require ('../Images/2.jpg'),
    require ('../Images/3.jpg'),
    require ('../Images/4.jpg'),
    require ('../Images/5.jpg'),
    require ('../Images/6.jpg'),
    require ('../Images/7.jpg'),
    require ('../Images/8.jpg'),
    require ('../Images/9.jpg'),
    require ('../Images/10.jpg'),
    require ('../Images/11.jpg'),
    require ('../Images/12.jpg'),
    require ('../Images/13.jpg'),
    require ('../Images/14.jpg'),
    require ('../Images/15.jpg'),
    require ('../Images/16.jpg'),
    require ('../Images/17.jpg'),
    require ('../Images/18.jpg'),
    require ('../Images/19.jpg'),
    require ('../Images/20.jpg'),
    require ('../Images/21.jpg'),
    require ('../Images/22.jpg'),
    require ('../Images/23.jpg'),
    require ('../Images/24.jpg'),
    require ('../Images/25.jpg'),
    require ('../Images/26.jpg'),
    require ('../Images/27.jpg'),
    require ('../Images/28.jpg'),
    require ('../Images/29.jpg'),
    require ('../Images/30.jpg'),
    require ('../Images/31.jpg'),
    require ('../Images/32.jpg'),
    

]