export const sliderPiramide = [

    require ('../ImagesPiramide/33.jpg'),
    require ('../ImagesPiramide/34.jpg'),
    require ('../ImagesPiramide/35.jpg'),
    require ('../ImagesPiramide/36.jpg'),
    require ('../ImagesPiramide/37.jpg'),
    require ('../ImagesPiramide/38.jpg'),
    require ('../ImagesPiramide/39.jpg'),
    require ('../ImagesPiramide/40.jpg'),
    require ('../ImagesPiramide/41.jpg'),
    require ('../ImagesPiramide/42.jpg'),
    require ('../ImagesPiramide/43.jpg'),
    require ('../ImagesPiramide/44.jpg'),
    require ('../ImagesPiramide/45.jpg'),
    require ('../ImagesPiramide/46.jpg'),
    require ('../ImagesPiramide/47.jpg'),
    require ('../ImagesPiramide/48.jpg'),
    require ('../ImagesPiramide/49.jpg'),
    require ('../ImagesPiramide/50.jpg'),
    require ('../ImagesPiramide/51.jpg'),
    require ('../ImagesPiramide/52.jpg'),
    require ('../ImagesPiramide/53.jpg'),
    require ('../ImagesPiramide/54.jpg'),
    require ('../ImagesPiramide/55.jpg'),
    require ('../ImagesPiramide/56.jpg'),
    require ('../ImagesPiramide/57.jpg'),
    require ('../ImagesPiramide/58.jpg'),
    require ('../ImagesPiramide/59.jpg'),
    require ('../ImagesPiramide/60.jpg'),
    require ('../ImagesPiramide/61.jpg'),
   
    require ('../ImagesPiramide/63.jpg'),
    require ('../ImagesPiramide/64.jpg'),
    require ('../ImagesPiramide/65.jpg'),
    
    require ('../ImagesPiramide/68.jpg'),
    require ('../ImagesPiramide/69.jpg'),
    require ('../ImagesPiramide/70.jpg'),
    require ('../ImagesPiramide/71.jpg'),
    require ('../ImagesPiramide/72.jpg'),
    require ('../ImagesPiramide/73.jpg'),
    require ('../ImagesPiramide/74.jpg'),
    require ('../ImagesPiramide/75.jpg'),
    require ('../ImagesPiramide/76.jpg'),
    require ('../ImagesPiramide/77.jpg'),
    require ('../ImagesPiramide/78.jpg'),
    require ('../ImagesPiramide/79.jpg'),
    require ('../ImagesPiramide/80.jpg'),
    require ('../ImagesPiramide/81.jpg'),
    
    

]